#!/usr/bin/env python3
"""Generate assets/maps/atlantis_sectors.json as annular wedges.

8 inner-ring + 8 outer-ring sectors, paired by radial slice (slice 1 = north,
clockwise). Layout is computed from ring radii + slice angle so sectors never
overlap. Tune the constants below and re-run; then re-run
gen_atlantis_placeholder.py so the baked map art tracks the same geometry.
"""
import json, math, os

CX, CY = 1024.0, 1024.0          # map center (2048x2048)
# Ring radii in px from center. Meteor core radius is 260, so the inner ring
# clears it. A radial gap separates the two rings.
R_INNER_LO, R_INNER_HI = 320.0, 600.0
R_OUTER_LO, R_OUTER_HI = 650.0, 950.0
# Label anchor radius per ring. Inner labels pushed toward the outer edge of
# the inner wedge so the 8 of them spread out (more circumference = less
# crowding near the top).
LABEL_R_INNER = 565.0
LABEL_R_OUTER = 800.0
PAD_DEG = 3.5                    # angular gap between adjacent wedges
ARC_PTS = 7                     # samples per arc edge

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(os.path.dirname(HERE), "assets", "maps", "atlantis_sectors.json")


def slice_center_deg(slice_no):  # slice 1 at top (north), clockwise
    return -90.0 + (slice_no - 1) * 45.0


def wedge(r_lo, r_hi, center_deg):
    half = 22.5 - PAD_DEG
    a0 = math.radians(center_deg - half)
    a1 = math.radians(center_deg + half)
    pts = []
    for i in range(ARC_PTS):  # inner arc a0 -> a1
        a = a0 + (a1 - a0) * i / (ARC_PTS - 1)
        pts.append([round(CX + r_lo * math.cos(a)), round(CY + r_lo * math.sin(a))])
    for i in range(ARC_PTS):  # outer arc a1 -> a0
        a = a1 + (a0 - a1) * i / (ARC_PTS - 1)
        pts.append([round(CX + r_hi * math.cos(a)), round(CY + r_hi * math.sin(a))])
    return pts


def anchor(r, center_deg):
    a = math.radians(center_deg)
    return [round(CX + r * math.cos(a)), round(CY + r * math.sin(a))]


names_inner = {1:"Command",2:"Refinery",3:"Foundry",4:"Geothermal",
               5:"Reality Log",6:"Genetics Lab",7:"Artifact Vault",8:"Transit Hub"}
names_outer = {1:"Docks",2:"Residential N",3:"Factory",4:"Farm",
               5:"Commons",6:"Medical",7:"Museum",8:"Residential S"}

sectors = []
for s in range(1, 9):
    c = slice_center_deg(s)
    sectors.append({"id": f"I-{s}", "name": names_inner[s], "ring": "inner", "slice": s,
                    "polygon": wedge(R_INNER_LO, R_INNER_HI, c),
                    "label_anchor": anchor(LABEL_R_INNER, c)})
for s in range(1, 9):
    c = slice_center_deg(s)
    sectors.append({"id": f"O-{s}", "name": names_outer[s], "ring": "outer", "slice": s,
                    "polygon": wedge(R_OUTER_LO, R_OUTER_HI, c),
                    "label_anchor": anchor(LABEL_R_OUTER, c)})

out = {
    "_comment": "Atlantis sector overlay. Annular-wedge layout generated by tools/gen_sectors.py from ring radii + 45-deg slices (slice 1 = north, clockwise). Coords in atlantis.png pixel space (2048x2048). Meteor core (r=260) sits inside the inner ring. Re-run gen_atlantis_placeholder.py after editing to keep the baked art aligned.",
    "sectors": sectors,
}
with open(OUT_PATH, "w") as f:
    json.dump(out, f, indent="\t")
print("wrote", len(sectors), "sectors ->", OUT_PATH)
